version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - "4466:4466"
    env_file:
      - .env
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            database: ${POSTGRES_DATABASE}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
